### ISSUE TITLE
Ply reader added to the MESH IO toolbox

### ISSUE THREAD

**Issue by rFalque** [llorz/SGA19_zoomOut#2]
Hi llorz,

I have been trying several of your repo on some of my data and it has been super helpful! However, the lack of ply interface is a bit annoying. I fixed it and added a wrapper for ply files that is transparent in the code but I keep copying and pasting the fix from one repo to another.

Can you let me know where I can push the fix to the MESH library?

Cheers,
Raphael

Ps: thanks a lot for sharing your code :)

**Comment by llorz** [comment]
Hi Raphael, 

Sorry for the late reply. I am really happy to hear that our code can be a bit helpful!

To add ply files, I guess the simplest way is: (1) add all the files to MESH/MESH_IO/private/ (2) then combine your wrapper with MESH.MESH_IO.read_shape. (Or simply call your wrapper inside read_shape). 

Please let me know if there is anything I can help you. 

Thanks, best regards, 
Jing
